import colorScheme from "@/constants/colorScheme";
import { StyleSheet } from "react-native";
import { s, scale } from "react-native-size-matters";

export const layout = StyleSheet.create({
  body: {
    width: "100%",
    height: "100%",
    backgroundColor: colorScheme.background,
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
  },
  header: {
    width: "100%",
    height: "15%",
    padding: scale(5),
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: scale(5),
  },
  content: {
    flex: 1,
    height: "70%",
    padding: scale(5),
    display: "flex",
    flexDirection: "row",
    // justifyContent: "space-between",
    alignContent: "flex-start",
    flexWrap: "wrap",
  },
  footer: {
    width: "100%",
    height: "15%",
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-end",
  },
});

export const header = StyleSheet.create({
  search: {
    flex: 1,
    height: "100%",
    fontSize: scale(30),
    color: colorScheme.text,
    borderColor: colorScheme.text,
    borderWidth: scale(1),
    borderRadius: scale(2),
    paddingLeft: scale(5),
    paddingBottom: scale(-7),
  },
  searchButton: {
    width: '20%',
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: scale(5),
    height: "100%",
    color: colorScheme.text,
    borderColor: colorScheme.text,
    borderWidth: scale(1),
    borderRadius: scale(2),
    paddingLeft: scale(5),
    paddingRight: scale(5),
  },
  searchButtonText: {
    color: colorScheme.text,
    fontSize: scale(20),
  },
});
export const footer = StyleSheet.create({
  search: {
    width: "30%",
    height: "100%",
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: scale(5),
    padding: scale(5),
  },
  searchBar: {
    width: "100%",
    height: "100%",
    fontSize: scale(30),
    color: colorScheme.text,
    borderColor: colorScheme.text,
    borderWidth: scale(1),
    borderRadius: scale(2),
    paddingLeft: scale(5),
    paddingBottom: scale(-5),
  },
  searchButton: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: scale(5),
    height: "100%",
    color: colorScheme.text,
    borderColor: colorScheme.text,
    borderWidth: scale(1),
    borderRadius: scale(2),
    paddingLeft: scale(5),
    paddingRight: scale(5),
  },
  scoutButtons: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    height: "100%",
    padding: scale(5),
    gap: scale(5),
  },
  scoutButton: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: scale(5),
    height: "100%",
    color: colorScheme.text,
    borderColor: colorScheme.text,
    borderWidth: scale(1),
    borderRadius: scale(2),
    paddingLeft: scale(5),
    paddingRight: scale(5),
  },
  plusButton: {
    borderColor: colorScheme.green,
  },
});
